services:
    postgres:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - craftboard_network
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:8.0.3
        restart: always
        container_name: redis-instance
        command: redis-server --requirepass ${REDIS_PASSWORD}
        networks:
            - craftboard_network
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
    ai-manager:
        build:
            context: ./ai-manager
            dockerfile: Dockerfile
        restart: always
        networks:
            - craftboard_network
        ports:
            - 8000:8000
        depends_on:
            - postgres
            - redis
        volumes:
            - root/main/craftboard/ai-manager/.env:/app/.env
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        environment:
            - NODE_ENV=development
            - PORT=3001
        networks:
            - craftboard_network
        ports:
            - 3000:3000
        depends_on:
            - postgres
            - redis
        volumes:
            - root/main/craftboard/frontend/.env:/app/.env
networks:
    craftboard_network:
        driver: bridge
        name: craftboard_network
